[workspace]
channels = ["conda-forge"]
name = "inventario"
platforms = ["linux-64", "osx-arm64", "win-64"]

[environments]
default = ["rust", "lint"]

[feature.rust.dependencies]
rust = "*"
rust-src = "*"
rust-std-wasm32-unknown-unknown = "*"
dioxus = "*"

[feature.rust.tasks]
serve = { cmd = "dx serve", description = "Serve the webapp" }

[feature.lint.dependencies]
prek = "*"
tombi = ">0.7.28"

[feature.lint.tasks]
prek = { cmd = "prek", description = "Run linters" }
