default_install_hook_types = ["pre-commit", "pre-push"]
exclude.glob = [".vscode/*"]

[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace" },
  { id = "check-added-large-files", args = ["--maxkb=1024"] },
  { id = "check-case-conflict" },
  { id = "end-of-file-fixer" },
  { id = "fix-byte-order-marker" },
  { id = "check-json" },
  { id = "check-json5" },
  { id = "check-toml" },
  { id = "check-yaml" },
  { id = "check-xml" },
  { id = "mixed-line-ending", args = ["--fix=lf"] },
  { id = "check-symlinks" },
  { id = "check-merge-conflict", args = ["--assume-in-merge"] },
  { id = "detect-private-key" },
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "rust-format"
name = "Format Rust files with Dioxus"
language = "system"
entry = "pixi run dx fmt"
pass_filenames = false
types = ["rust"]

[[repos.hooks]]
id = "toml-format"
name = "Format TOML files with Tombi"
language = "system"
entry = "pixi run tombi format"
files.glob = "*.toml"

[[repos.hooks]]
id = "rust-clippy"
name = "Lint Rust files with cargo clippy"
language = "system"
entry = "pixi run cargo clippy"
pass_filenames = false
types = ["rust"]
stages = ["pre-push"]
